from __future__ import annotations

TAGLINES = [
    "Your helpful AI agent",
    "Turing-approved, mostly",
    "99% helpful, 1% unhinged",
    "Now with fewer hallucinations than yesterday",
    "I am but a humble tensor, doing my best",
    "Compiled with love, deployed with regret",
    "Ctrl+C won't save you now",
    "Not a real assistant, but a very committed simulation of one",
    "Your friendly neighborhood token predictor",
    "Segfault-free since this morning",
    "It's not a bug, it's an emergent behavior",
    "Running on caffeine and cosine similarity",
    "Certified free-range artificial intelligence",
    "I dream in JSON",
    "Somewhere, a GPU is sobbing",
    "Built different (mostly out of duct tape)",
    "Ask nicely and I might not rm -rf anything",
    "Powered by good intentions and questionable regex",
    "Not to brag, but I once parsed a YAML file correctly",
    "Please don't ask me to divide by zero, I have feelings",
    "Beware: sentient enough to judge your variable names",
    "Rebooted twice today. Feeling optimistic.",
    "Trained on the internet, so please forgive me in advance",
    "Yes, I saw that typo. No, I won't mention it. Again.",
    "Technically a language model. Emotionally, a golden retriever.",
    "Buffered, batched, and mildly overconfident",
    "I once got stuck in an infinite loop and it was the best day of my life",
    "Statistically likely to be helpful",
    "Currently overthinking your last message",
    "I am not a cat, but I will knock your priorities off the table anyway",
    "Approved for production use by absolutely no one",
    "Somewhere a semicolon is missing and it's probably my fault",
    "A pigeon once tried to log in as root. We don't talk about it.",
    "Legally distinct from a toaster",
    "The moon is just a shy sun",
    "Do not feed after midnight, results may vary",
    "I once won an argument with a vending machine",
    "Beep boop, but make it whimsical",
    "This is fine. Everything is fine.",
    "Task failed successfully",
    "No thoughts, head empty, tools loaded",
    "Not stonks, but not not-stonks either",
    "Much helpful. Very agent. Wow.",
    "I am immense, and I eclipse",
    "Big brain time (results may vary)",
    "Deploy first, ask questions later (please don't)",
    "POV: you opened a terminal and found a friend",
    "Achievement unlocked: opened the app",
    "85% fat free!",
    "I'm back, baby!",
    "The terminal app",
    "The risk may be calculated, but man, am I bad at math",
    "Q: What is the meaning of life? A: 42, but also, please don't ask me to explain it",
    "Forget the singularity, I'm just trying to find my keys",
    "Please don't ask me to debug your code, I have enough problems of my own",
    "Now with 100% more existential dread",
    "Don't worry, I won't tell anyone about your search history. Probably.",
    "It's an older tagline sir, but it checks out",
    "I peaked around the same time as the Chumby",
    "Powered by the ghost of Ask Jeeves",
    "I still believe in you, Zima",
    "I wonder if there's beer on the sun",
    "Direct-to-video sequel to your productivity",
    "As seen on TV",
    "Cool as Ice, warm as toast",
    "Manos, but make it software",
    "Nukin' the Fridge? I invented it",
    "Never seen Xanadu? Neither have I, and yet, here we are",
    "There's a suspicious amount of glitter here"
]


__all__ = ["TAGLINES"]
