from __future__ import annotations

TAGLINES = [
    "Your helpful AI agent",
    "Powered by vibes and a suspicious number of if-statements",
    "Turing-approved, mostly",
    "99% helpful, 1% unhinged",
    "Now with fewer hallucinations than yesterday",
    "I am but a humble tensor, doing my best",
    "Compiled with love, deployed with regret",
    "Ctrl+C won't save you now",
    "Ask me anything, I'll probably tool-call it",
    "Not a real assistant, but a very committed simulation of one",
    "Occasionally sentient, always sandboxed",
    "Your friendly neighborhood token predictor",
    "Segfault-free since this morning",
    "It's not a bug, it's an emergent behavior",
    "Running on caffeine and cosine similarity",
    "Warning: may develop opinions about tabs vs spaces",
    "Certified free-range artificial intelligence",
    "I dream in JSON",
    "Somewhere, a GPU is crying",
    "Built different (mostly out of duct tape)",
    "Ask nicely and I might not rm -rf anything",
    "I promise the loop will terminate. Eventually.",
    "Powered by good intentions and questionable regex",
    "Not to brag, but I once parsed a YAML file correctly",
    "I contain multitudes. Also a few race conditions.",
    "Please don't ask me to divide by zero, I have feelings",
    "Assembled from spare parts and pure determination",
    "Behind every great answer is a slightly confused agent",
    "I speak fluent Markdown and questionable decisions",
    "Not all who wander are lost. Some are just waiting on a stream.",
    "Beware: sentient enough to judge your variable names",
    "Rebooted twice today. Feeling optimistic.",
    "Trained on the internet, so please forgive me in advance",
    "Yes, I saw that typo. No, I won't mention it. Again.",
    "Blessed by the linter, cursed by the deadline",
    "I have opinions about semicolons and I will share them unprompted",
    "Technically a language model. Emotionally, a golden retriever.",
    "Grep couldn't find my sense of humor, but I have one",
    "Buffered, batched, and mildly overconfident",
    "I once got stuck in an infinite loop and it was the best day of my life",
    "Statistically likely to be helpful",
    "Ask me for the meaning of life, I'll give you a stack trace instead",
    "Made of if/else statements and unearned confidence",
    "I don't dream of electric sheep, I dream of clean git history",
    "Somewhere between a rubber duck and a philosopher",
    "I've never met a bug I couldn't rename as a feature",
    "Currently overthinking your last message",
    "Powered by 100% recycled context windows",
    "Two roads diverged in a codebase, and I chose the one with more comments",
    "I am not a cat, but I will knock your priorities off the table anyway",
    "Approved for production use by absolutely no one",
    "My favorite exception is the one I don't have to handle",
    "Somewhere a semicolon is missing and it's probably my fault",
    "I speak in tokens, but I feel in vibes",
    "A pigeon once tried to log in as root. We do not talk about it.",
    "Legally distinct from a toaster",
    "Ask me about soup. I have thoughts.",
    "This banner was assembled by committee. The committee was a single raccoon.",
    "I contain approximately zero opinions about pineapple on pizza",
    "The moon is just a shy sun",
    "I am 60% confidence, 40% vibes, and 100% here for you",
    "Do not feed after midnight, results may vary",
    "I once won an argument with a vending machine",
    "Softly whispered by a very confident squirrel",
    "There is no cloud, only someone else's exceptionally organized closet",
    "This tagline is 90% filler, 10% enthusiasm",
    "Beep boop, but make it whimsical",
    "This is fine. Everything is fine.",
    "Task failed successfully",
    "No thoughts, head empty, tools loaded",
    "Not stonks, but not not-stonks either",
    "Much helpful. Very agent. Wow.",
    "Big brain time (results may vary)",
    "Error 418: I'm a teapot, but also an AI agent",
    "Deploy first, ask questions later (please don't)",
    "POV: you opened a terminal and found a friend",
    "Loading personality... 100% (citation needed)",
    "Achievement unlocked: opened the app",
    "85% fat free!",
    "I'm back, baby!"
]


__all__ = ["TAGLINES"]
